### ISSUE TITLE
useFetch cache

### ISSUE THREAD

**Issue by iamthesiz** [rrostt/tesla-dashboard-home#1]
It looks like you require localStorage caching (aka persistent caching). This is something `use-http` will be offering in the future, just haven't gotten to it yet.

**Comment by rrostt** [comment]
Sounds good. Do you take PRs @alex-cory ?

**Comment by iamthesiz** [comment]
I do!

**Comment by iamthesiz** [comment]
I was thinking about adding an options like
```js
useFetch({
  persist: true, // false by default
})
```
This would use `localStorage` if in browser or `AsyncStorage` if you're in react-native.
It would probably be a good idea to use this in conjunction with `cacheLife` so that your app will still fetch data at a certain point so state doesn't get stale.

**Comment by iamthesiz** [comment]
For now you probably don't have to worry about react-native. We'll just put in the docs that `persist` doesn't work yet with react-native

**Comment by iamthesiz** [comment]
I'll close this unless you want it open. Thanks for your help!

**Comment by rrostt** [comment]
It was my pleasure @alex-cory !
